FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

ENV DATA_SERVICE_URL=http://data_service:5001
ENV ANALYTICS_SERVICE_URL=http://analytics_service:5002

COPY micro/api_gateway.py ./api_gateway.py

EXPOSE 5000
CMD ["python", "api_gateway.py"]
