FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY data ./data
COPY micro/data_service.py ./data_service.py

EXPOSE 5001
CMD ["python", "data_service.py"]
